language: python
python:
  - "2.6"
  - "2.7"

install: "pip install coverage"

script:
  - "cd oblig02"
  - "coverage run -a --branch PreTeX/prepro.py tests/e2e/testfiles/tex_before.xtex /dev/null -q"
  - "coverage run -a --branch --source=PreTeX `which py.test`"
  - "coverage report -m --fail-under=85 --omit=\"*__init__.py\",\"*argparse*\""

notifications:
  email:
    recipients: nicolai.skogheim@gmail.com
    on_success: change # default: change
    on_failure: change # default: always
