language: python
python:
  - "2.6"
  - "2.7"

script: "py.test --cov oblig02/PreTeX/"

notifications:
  email:
    recipients: nicolai.skogheim@gmail.com
    on_success: change # default: change
    on_failure: change # default: always
